# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a56360172d563b87fad3848dfac15da1a13d062607c35dce02ea847ef6c4ecc6c563d6601d19679bf8c78769d575bf24b06c11aac1e5b005131a2e0c6c9c221b

test:
  secret_key_base: 28e06554fc1f4fbed0dee1c937437afcdb719e09e00f850c19c35c80ff2576ab7cacaf58f3f6101a917263765cb71c4fada0d549438386024cd19d463581bac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
